"""Added file_requests table.

Revision ID: 1f7f0374132f
Revises: 15bc2c528991
Create Date: 2024-04-24 08:47:13.523890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7f0374132f'
down_revision = '15bc2c528991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_requests',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('dispatcher_user_id', sa.Integer(), nullable=False),
    sa.Column('storage_runner_user_id', sa.Integer(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected', name='request_status'), nullable=True),
    sa.ForeignKeyConstraint(['dispatcher_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ),
    sa.ForeignKeyConstraint(['storage_runner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_requests')
    # ### end Alembic commands ###
